### ISSUE TITLE
MJML compiler in TCP mode failing in CI on bitbucket

### ISSUE THREAD

**Issue by bramski** [liminspace/django-mjml#119]
I'm having some issues getting our CI builds to pass using MJML-django in TCP mode as the renderer. It was working and then quite consistently when we started rendering more emails they started failing:

```
RuntimeError: MJML compile error (via MJML TCP server): no working server
Number of servers: 1
Timeouts: 0
```
I'm a bit baffled by the error. It appears that there are working servers but the compilation step is failing immediately.

Bitbucket YAML looks as follows for docker config:
```
image: python:3.6-jessie

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: pipelines
        MYSQL_ROOT_PASSWORD: *********
    redis:
      image: redis
    mjml:
      image: liminspace/mjml-tcpserver:0.10.2
      environment:
        HOST: "0.0.0.0"
        PORT: "28102"
      expose:
          - "28102"
      ports:
          - "28102:28102"
```
