### ISSUE TITLE
Getting timeouts since 0.8.0

### ISSUE THREAD

**Issue by Flexonze** [liminspace/django-mjml#90]
Hi, i've upgraded django-mjml to version to 0.8.0 while trying to fix the [issue I had](https://github.com/liminspace/django-mjml/issues/63). But now i'm getting timeouts. I don't really know why. Im using the docker-compose image.
```
MJML compile error (via MJML TCP server): no working server
Number of servers: 1
Timeouts: 1
```

**Comment by liminspace** [comment]
@Flexonze
Do you use updated tcpserver.js? 
If you use tcpserver in docker be sure you use latest or 0.8 tag.

**Comment by Flexonze** [comment]
I am using latest
```
  mjml:
    image: liminspace/mjml-tcpserver:latest
    environment:
      MJML_ARGS: "--mjml.minify=true --mjml.validationLevel=strict"
```
